# Isolate version package from others.

load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

bzl_library(
    name = "version_names_bzl",
    srcs = ["version_names.bzl"],
    visibility = ["//visibility:private"],
)
